= Globus Cloud Service Deployment Examples

For over a decade, Globus has provided a cloud hosted data management service to the non-profit research community.  Globus service deployment practices and processes are continually changing, from manual deployment to Chef orchestrated deployment to the most recent practice of serverless deployment. In our experience, deploying a cloud hosted service can be easy, but deploying a robust, secure service in a cost and time efficient manner at scale is a challenge.  Here we share sample deployment scripts and templates to provide an example of some of the cloud deployment practices of a secure, reliable, and scalable service.

The Globus service is architected as a set of services, each with its own RESTful API deployed on Amazon Web Services. To support a robust software release cycle, Globus deploys these services across several infrastructure environments, such as sandbox, integration, testing, staging, preview, and production.  Each environment has its own unique deployment requirements when considering factors such as availability, performance, cost, scale, backup, logging, monitoring, and security. Globus operations adhere to the principle of infrastructure as code, primarily using a declarative approach. There are several advantages to this approach, particularly when coupled with automation where practicable. Fewer deployment errors and increased efficiency are key benefits. The ability to apply source control best practices to our infrastructure deployment processes has enabled better change control and configuration management. The decrease in deploy times has made it easier to replicate and standardize environments. 

Select Globus services have adopted a serverless deployment model using Docker containers managed by AWS Fargate. A link:deploy.sh[script] is used to deploy and provision the AWS infrastructure that runs the containers. The script first packages resources, such as AWS Lambda functions, by zipping the resource, uploading it to AWS S3, and then creating a reference to the resource that can be used by CloudFormation.  Next, CloudFormation templates are run that provision link:shared.yaml[shared infrastructure] and link:environment.yaml[environment specific infrastructure], such as Docker images, backup infrastructure, databases, logs, Security Groups, and Elastic Load Balancers. Alternatively, separate CloudFormation templates can be run for the application and the application infrastructure.  Separate templates allow isolation of resources that are updated infrequently, such as databases, thereby mitigating the risks of environment changes. The script then outputs a change set and a description of how each change will be applied, e.g., whether a database will be updated in place or whether it will be deleted and replaced. The change set is manually reviewed before deployment proceeds to ensure changes will not cause service downtime or data loss, for example deletion and creation of resources rather than updating resource in place. Last, the change set is applied to the environment.

Docker images are built from link:Dockerfile[Docker image files], and source code is installed on the image.  At present Docker image creation and source code installation are performed on a local workstation. Images are then pushed to AWS Elastic Container Registry.  Assuming this is an update of an existing environment, a command is run to retire old images and update the AWS Elastic Container Service to start containers using the most recent image in the registry.  link:docker-compose.yaml[Docker Compose] can be used to build images and (for development purposes) run them on a local workstation. Planned improvements in this process include automatically triggering versioned image builds when source code is committed to the GitHub repository and retaining previous image versions to facilitate roll back.

== Sample Deploy Tools
- link:deploy.sh[Deploy script]
- link:shared.yaml[CloudFormation template for shared infrastructure]
- link:environment.yaml[CloudFormation template for environment specific infrastructure]
- link:Dockerfile[Docker image file]
- link:docker-compose.yaml[Docker Compose file]

== Suggested Resources
- link:https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html[Docker Basics for Amazon ECS]
- link:https://aws.amazon.com/fargate/faqs/[AWS Fargate FAQ]
- link:https://aws.amazon.com/cloudformation/faqs/[CloudFormation FAQ]
